[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v2/task_scripts/"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 16000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 60

[GLOBAL_OPTS]
data_ext = 'smooth_avg_vis.uvh5'
cal_ext = 'smooth_abs.calfits'
spw0 = 48
spw1 = 320
label = "low-band-v2-wide-dly-h2cflags"
labelin="low-band-v2"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags/"
flag_ext="og_flags1"
time_threshold = 0.02
chunk_size=60
nbl_per_load = "none"
t_avg = 300.0
#t_avg = "none"
#n_avg = 32
final_flag_ext = "total_threshold_and_a_priori_flags.h5"
final_cal_ext = "smooth_abs.calfits"

[DELAY_OPTS]
tol = 1e-9
standoff = 100
min_dly = 1000
calibration = "none"
filter_mode = "DPSS"
# we may want to consider another flagging round after delay filtering.

[XTALK_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.025
tol = 1e-9
# inpaint beyond frate limit by this much.
frate_standoff = 1.0

[ROTOFLAG_OPTS]
percentile_freq = 99.0
percentile_time = 99.0
niters = 10
kf_size = 8
kt_size = 32

[PSPEC_OPTS]
nspws = 2
beam_file="/lustre/aoc/projects/hera/aewallwi/HERA-Beams/NicolasFagnoniBeams/NF_HERA_Vivaldi_efield_beam_healpix.fits"

[FILTER_CLEANUP_OPTS]
clear_xtalk_cache = false
clear_delay_cache = false
clear_delay = false



############################################################################################################

[WorkFlow]
actions = [
           "RED_AVERAGE_GROUP",
           "PRE_CHUNK",
           #"DELAY_ROUND1",
           #"ROTOFLAG_METRIC",
           #"ROTOFLAG_FLAG",
           "CALIBRATE_AUTOS",
           "DELAY_ROUND2_INIT",
           "XTALK",
           "TIME_AVERAGE",
           "RECONSTITUTE",
           "PSPEC",
           "COMBINE_PSPEC"]#,
	         #"FILTER_CLEANUP"]

[RED_AVERAGE_GROUP]
mem=16000
chunk_size=1
stride_length=4
args=["{basename}", "${GLOBAL_OPTS:labelin}", "${GLOBAL_OPTS:data_ext}",
      "${GLOBAL_OPTS:cal_ext}", "4",
      "${GLOBAL_OPTS:spw0}", "${GLOBAL_OPTS:spw1}", "${GLOBAL_OPTS:yaml_dir}"]

[PRE_CHUNK]
mem=24000
prereqs="RED_AVERAGE_GROUP"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${GLOBAL_OPTS:labelin}", "${GLOBAL_OPTS:data_ext}",
      "${GLOBAL_OPTS:cal_ext}", "${GLOBAL_OPTS:chunk_size}",
      "${GLOBAL_OPTS:spw0}", "${GLOBAL_OPTS:spw1}"]

[DELAY_ROUND1]
#prereqs="PRE_CHUNK"
prereq_chunk_size="all"
mem = 16000
chunk_size=1
stride_length="${Options:chunk_size}"
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:flag_ext}",
        "${GLOBAL_OPTS:label}",
        "${DELAY_OPTS:tol}", "${DELAY_OPTS:standoff}", "${GLOBAL_OPTS:time_threshold}", "${GLOBAL_OPTS:cache_dir}",
        "${GLOBAL_OPTS:yaml_dir}"]

[ROTOFLAG_METRIC]
prereqs = "DELAY_ROUND1"
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${GLOBAL_OPTS:label}", "${GLOBAL_OPTS:data_ext}",
      "${ROTOFLAG_OPTS:kf_size}", "${ROTOFLAG_OPTS:kt_size}"]

[ROTOFLAG_FLAG]
prereqs = "ROTOFLAG_METRIC"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args=["{basename}", "${GLOBAL_OPTS:label}",
      "${ROTOFLAG_OPTS:percentile_freq}", "${ROTOFLAG_OPTS:percentile_time}",
      "${ROTOFLAG_OPTS:niters}", "${GLOBAL_OPTS:cal_ext}"]

[CALIBRATE_AUTOS]
prereqs = "PRE_CHUNK"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args=["{basename}", "${GLOBAL_OPTS:labelin}", "${GLOBAL_OPTS:label}",
      "${GLOBAL_OPTS:data_ext}",
      "${GLOBAL_OPTS:nbl_per_load}", "${GLOBAL_OPTS:pols}", "${GLOBAL_OPTS:final_flag_ext}",
      "${GLOBAL_OPTS:final_cal_ext}"]

[DELAY_ROUND2_INIT]
prereqs = "CALIBRATE_AUTOS"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:final_flag_ext}", "${GLOBAL_OPTS:labelin}",
        "${GLOBAL_OPTS:label}", "${DELAY_OPTS:tol}",
        "${DELAY_OPTS:standoff}",   "${DELAY_OPTS:min_dly}", , "${GLOBAL_OPTS:cache_dir}",
        "${DELAY_OPTS:filter_mode}", "${GLOBAL_OPTS:pols}"]

[XTALK]
prereqs = "DELAY_ROUND2_INIT"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 32000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}",
        "${GLOBAL_OPTS:label}", "${XTALK_OPTS:tol}",
        "${XTALK_OPTS:frmax0}", "${XTALK_OPTS:frmax1}", "${XTALK_OPTS:frate_standoff}", "${GLOBAL_OPTS:cache_dir}"]

[TIME_AVERAGE]
prereqs= "XTALK"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem=16000
args=["{basename}",
      "${GLOBAL_OPTS:data_ext}",
      "${GLOBAL_OPTS:label}",
      "${GLOBAL_OPTS:t_avg}"]#, "${GLOBAL_OPTS:n_avg}"]


[RECONSTITUTE]
prereqs = "TIME_AVERAGE"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:label}"]

[PSPEC]
prereqs = "RECONSTITUTE"
prereq_chunk_size="all"
mem=128000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:label}",
      "${PSPEC_OPTS:beam_file}", "${PSPEC_OPTS:nspws}",
      "${DELAY_OPTS:standoff}", "${DELAY_OPTS:tol}", "${GLOBAL_OPTS:final_flag_ext}"]

[COMBINE_PSPEC]
prereqs = "PSPEC"
prereq_chunk_size="all"
mem = 64000
chunk_size=1
stride_length="${Options:chunk_size}"
args = ["{basename}", "${GLOBAL_OPTS:label}"]

[FILTER_CLEANUP]
prereqs = "COMBINE_PSPEC"
prereq_chunk_size="all"
mem = 16000
chunk_size=1
stride_length="${Options:chunk_size}"
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:label}"]
