[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v2/lst_binning/task_scripts/"
source_script = "~/.bashrc"
conda_env = "hera3dev"
base_mem = 80000
base_cpu = 4
timeout = "48h"
pbs_mail_user = "aewallwi+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "False"
Nbls_to_load = 100
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 60
dlst = 0.0007046864745507975
lst_start = 5.178260914725223 # this is before the first LST on 2459118 and after the last LST on 2459139
fixed_lst_start = "True"
vis_units = "Jy"
parallelize = "True"
average_redundant_baselines = "False"
file_ext = "grp1.of1.{type}.{time:7.5f}.sum.uvh5"
outdir = "/lustre/aoc/projects/hera/H4C/lstbin/before_filtering_before_red_averaging"
parent_dir = "/lustre/aoc/projects/hera/H4C/makeflow/lstbin_before_filtering_before_red_averaging_sum"
data_files = ["/lustre/aoc/projects/hera/H4C/2459118/zen.*.sum.uvh5",
              "/lustre/aoc/projects/hera/H4C/2459119/zen.*.sum.uvh5",
              "/lustre/aoc/projects/hera/H4C/2459122/zen.*.sum.uvh5",
              "/lustre/aoc/projects/hera/H4C/2459139/zen.*.sum.uvh5",
              ]
calibration = "'smooth_abs.calfits'"
flag_thresh = 0.8


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "flag_thresh", "average_redundant_baselines", "calibration"]
