#! This is a *template* file for the lstbin makeflow. Use `herapipes lstbin-setup` to 
#! generate specific lstbin makeflows for different cases. This template has a few 
#! variables that can be used to generate a makeflow for a specific case. These are:
#!   {{ REPODIR }}    : the directory of the hera-pipelines repo 
#!   {{ SEASON }}     : the season to process
#!   {{ IDR }}        : the IDR major number
#!   {{ GENERATION }} : the IDR generation number
#!   {{ ANALYSISDIR }}: the top-level directory where the analysis is being done
#!   {{ CASENAME }}   : the name of the case (e.g. "redavg-abscal-inpaint")
#!   {{ INPAINT_EXTENSION }} : the extension of the where_inpainted files: eiter "none" or ".where_inpainted.h5", depending on the case.
#!   {{ DATA_EXTENSION }} : the extension of the data files -- set by the case (e.g. "abs_calibrated.red_avg.inpaint.uvh5")
#!   {{ INPAINT_FORMAT }} : this gets set to "{inpaint_mode}/" if the case uses inpaint mode
#!   {{ CALEXT }}     : specifies the calfits file extension, or none if datafiles are already calibrated (e.g. ".smooth.calfits")
#! Note that all lines starting with '#!' will be removed in the created TOML file.
# This is the lstbin TOML file for the {{ CASENAME }} case.

[Options]
makeflow_type = "lstbin-notebook"
path_to_do_scripts = "{{ REPODIR }}/pipelines/{{ SEASON }}/idr{ IDR }}/v{ GENERATION }}/lstbin/task_scripts/"                                                                                           source_script = "~/.bashrc"
conda_env = "{{ SEASON }}"
base_mem = 12000
base_cpu = 1
timeout = "48h"

[LSTBIN_OPTS]                                                                                                                                                                                                                                                                                                                                                                                               # ---- Parameters used by hera_opm to build the makeflow ----
outdir = "${LSTAVG_OPTS:outdir}"                                                                                                                                                                      parallelize = true

           
[FILE_CFG]
# This section specifies a file configuration for LST-binning.
# The possible parameters here any input attribute of the
# LSTBinConfiguration class in hera_cal.lst_stack.config.
# The 'datafiles' section can contain any parameter that is
# passed to the `.find_datafiles()` method of that class.

nlsts_per_file = 2
lst_start = 0.0
antpairs_from_last_file_each_night = true
where_inpainted_file_rules = [
  [".sum.*.uvh5", ".where_inpainted.h5"]
]

[FILE_CFG.datafiles]                                                                                                                                                                                # Arguments to specify input files.
# Files to be read will be:
#    {datadir}/{nightdir}/zen.{jdglob}.{sd}.{label}[.]{extension}
datadir="/lustre/aoc/projects/hera/h6c-analysis/IDR{{ IDR }}/"
nightdirs=[
             "2459861", "2459862", "2459863", "2459864",
  "2459866", "2459867", "2459868", "2459869",
  "2459870", "2459871", "2459872", "2459873", "2459874",
             "2459876"                                                                                                                                                                                ]
label = "{{ DATA_EXTENSION }}"
sum_or_diff = "sum"
jdglob = "*"                                                                                                                                                                                           plot_every=180  # about 1 hour

[LSTAVG_OPTS]
# Options for the notebook running -- i.e. the metrics and averaging.
outdir = "/lustre/aoc/projects/hera/h6c-analysis/IDR{{ IDR }}/lstbin-outputs/{{ CASENAME }}/"
bl_chunk_size = 5000
fname_format = "{inpaint_mode}/zen.{kind}.{lst:7.5f}.sum.uvh5"
overwrite=true
write_med_mad=true

                                                                                                                                                                                                      # ========================================= THE WORKFLOW ========================
[WorkFlow]
actions = ["PER_OUTFILE_LSTSTACK_METRICS_NOTEBOOK"]

[PER_OUTFILE_LSTSTACK_METRICS_NOTEBOOK]
args = [
  "outdir", "lstconf", "lstavg_toml_file", "output_file_select", "kernel", "make_plots"
]