# This runs the lstbin-inspect notebook on a particulat LST-output directory.
# NOTE: to create the .mf file, execute build_makeflow_from_config.py -c ltbin-inspect.toml /path/to/lstbin-outputs/* (i.e. the basename is a folder).

[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR2/src/hera_pipelines/pipelines/h6c/idr2/v2/lstbin/task_scripts"
source_script = "~/.bashrc"
conda_env = "h6c"
base_mem = 250000
base_cpu = 1
timeout = "24h"
mail_user = "steven.g.murray@asu.edu"

[INSPECT_OPTS]
lstbin_outputs="/lustre/aoc/projects/hera/h6c-analysis/IDR2/lstbin-outputs"
notebook_dir="/lustre/aoc/projects/hera/h6c-analysis/IDR2/notebooks/lstbin-inspect"

# ========================================= THE WORKFLOW ========================
[WorkFlow]
actions = ["LSTBIN_INSPECT"]

[LSTBIN_INSPECT]
args = [
  "{basename}",
  "${INSPECT_OPTS:lstbin_outputs}",
  "${INSPECT_OPTS:notebook_dir}",
  "${Options:conda_env}",
]
