[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/lustre/aoc/projects/hera/Validation/test-4.1.0/software/hera_pipelines/pipelines/validation/h1c_idr3_2/task_scripts"
source_script = "~/.bashrc"
conda_env = "h1c_idr3_2_validation_lstbin"
base_mem = 196000
base_cpu = 1
timeout = "48h"
pbs_mail_user = "jsdillon+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "True"
Nbls_to_load = 100
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 60
dlst = 0.001565970008
lst_start = 4.711094445 # this is before the first LST on 2458041 and after the last LST on 2458208
vis_units = "Jy"
parallelize = "True"
file_ext = "grp1.of1.{type}.{time:7.5f}.sum.uvh5"
outdir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/LSTBIN/epoch_0"
parent_dir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/LSTBIN/epoch_0"
data_files = ["/lustre/aoc/projects/hera/Validation/test-4.1.0/2458041/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458042/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458043/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458044/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458045/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458046/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458047/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458048/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458049/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458050/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458051/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458052/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458058/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458059/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458062/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458063/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458064/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458067/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458068/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458069/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458070/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458071/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458072/zen.*.sum.smooth_calibrated.uvh5"]
calibration = "''"


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "calibration"]
