[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v1/task_scripts/"
conda_env = "hera3"
source_script = "~/.bashrc"
base_mem = 16000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 60

[GLOBAL_OPTS]
data_ext = 'smooth_avg_vis.uvh5'
cal_ext = 'smooth_abs.calfits'
spw0 = 48
spw1 = 320
label = "low-band-rtp-flags"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags/"
time_threshold = 0.02
chunk_size=60
nbl_per_load = 0
#t_avg = 300.0
t_avg = "none"
n_avg = 32
flag_ext = "total_threshold_and_a_priori_flags.h5"
final_cal_ext = "smooth_abs.calfits"

[DELAY_OPTS]
tol = 1e-9
standoff = 200
calibration = "none"

# we may want to consider another flagging round after delay filtering.
[PSPEC_OPTS]
nspws = 2
beam_file="/lustre/aoc/projects/hera/aewallwi/HERA-Beams/NicolasFagnoniBeams/NF_HERA_Vivaldi_power_beam_healpix.fits"



############################################################################################################

[WorkFlow]
actions = [
           "TIME_AVERAGE",
           "PSPEC",
           "COMBINE_PSPEC"]#,
	         #"FILTER_CLEANUP"]


[TIME_AVERAGE]
chunk_size=1
stride_length="${Options:chunk_size}"
mem=16000
args=["{basename}",
     "${GLOBAL_OPTS:data_ext}",
     "${GLOBAL_OPTS:label}",
     "${GLOBAL_OPTS:t_avg}"]

[PSPEC]
prereqs = "TIME_AVERAGE"
prereq_chunk_size="all"
mem=128000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:label}",
     "${PSPEC_OPTS:beam_file}", "${PSPEC_OPTS:nspws}",
     "${DELAY_OPTS:standoff}", "${DELAY_OPTS:tol}", "${GLOBAL_OPTS:flag_ext}"]


[COMBINE_PSPEC]
##prereqs = "PSPEC"
prereq_chunk_size="all"
mem = 64000
chunk_size=1
stride_length="${Options:chunk_size}"
args = ["{basename}", "${GLOBAL_OPTS:label}"]
