[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/usr/local/hera/hera_pipelines/pipelines/calamity/task_scripts"
data_folder = '19KTJjXlZTz_o4lKpgyzp21Ae13Xupw_b'
cal_folder = '1xOkUndpubolT7R66fFggnH6ZpE_Gnqgq'
secrets_dir = '/users/aewallwi/'
base_mem = 14500
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"
source_script = "/usr/local/miniconda3/etc/profile.d/conda.sh"
conda_env = "calamity"

[WorkFlow]
actions = ["DOWNLOAD",
           "PREPROCESS",
           "CLEANUP"]

[DOWNLOAD]
mem = 14500
args = ["{basename}",
       "${Options:data_folder}",
       "${Options:cal_folder}",
       "${Options:secrets_dir}"
      ]
[PREPROCESS]
prereqs = "DOWNLOAD"
prereq_chunk_size = 1
mem = 58000
args = ["{basename}"]

[CLEANUP]
prereqs = "PREPROCESS"
prereq_chunk_size = "all"
args = ["{basename}"]
