[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/gain_jumps/non_red_fringe_rate/task_scripts"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 16000
base_cpu = 1
timeout = "24h"
mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 8
spw_ranges='10~320,515~717,770~1090'
label = "fix-gain-jumps-long-delay-clean-include-variable-ants"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags_include_variable/"
nbl_per_load = 100

[DELAY_OPTS]
tol = 1e-9
standoff = 50.0
min_dly = 250.0
calibration = "none"
filter_mode = "DPSS"
spw_ranges = "0~310,310~832"
# we may want to consider another flagging round after delay filtering.

[FR_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.025
tol = 1e-9
# inpaint beyond frate limit by this much.
frate_standoff = 0.0
min_frate = 0.5

############################################################################################################

[WorkFlow]
actions = ["PRE_CHUNK",
           "DELAY",
           "TIME_INPAINT",
           "RECONSTITUTE",
           "MODEL_CALIBRATION",
           "SMOOTH_CAL_FREQ",]
           #"CLEANUP"]

[PRE_CHUNK]
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}",
    "${Options:chunk_size}",
    "${Options:spw_ranges}", "${Options:yaml_dir}"]

[DELAY]
prereqs = "PRE_CHUNK"
prereq_chunk_size = 1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}",
       "${Options:label}", "${DELAY_OPTS:tol}",
       "${DELAY_OPTS:standoff}",   "${DELAY_OPTS:min_dly}", "${Options:cache_dir}",
       "${Options:nbl_per_load}", "${DELAY_OPTS:spw_ranges}"]

[TIME_INPAINT]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}",
       "${Options:label}", "${FR_OPTS:tol}",
       "${FR_OPTS:frate_standoff}", "${FR_OPTS:min_frate}",
       "${Options:cache_dir}", "${DELAY_OPTS:spw_ranges}"]



[RECONSTITUTE]
prereqs = "TIME_INPAINT"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}",
       "${Options:label}"]

[MODEL_CALIBRATION]
prereqs="RECONSTITUTE"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:label}"]


[SMOOTH_CAL_FREQ]
prereqs="MODEL_CALIBRATION"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:label}"]

[CLEANUP]
prereqs="SMOOTH_CAL_FREQ"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem=16000
args = ["{baseneame}", "${Options:label}"]
