[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/hera_pipelines/pipelines/calamity/dpss_calibrate/task_scripts"
base_mem = 16000
base_cpu = 2
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"
conda_env = "hera3"
source_script = "~/.bashrc"

[DELAY_OPTS]
horizon=1.0
offset=25.0
min_dly=100.0

[SELECT_OPTS]
bllen_min=0.0
bllen_max=250.0
bl_ew_min=0.0

[WorkFlow]
actions = ["DPSS_CALIBRATE"]

[DPSS_CALIBRATE]
mem = 32000
args = ["{basename}", "${DELAY_OPTS:horizon}",
        "${DELAY_OPTS:offset}", "${DELAY_OPTS:min_dly}", "${SELECT_OPTS:bllen_min}",
        "${SELECT_OPTS:bllen_max}", "${SELECT_OPTS:bl_ew_min}"]
