[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/hera_pipelines/pipelines/calamity/dpss_calibrate/task_scripts"
base_mem = 64000
base_cpu = 4
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"
conda_env = "hera3gpu"
source_script = "~/.bashrc"
gres = "gpu"

[DELAY_OPTS]
horizon=1.0
offset=100.0
min_dly=0.0

[SELECT_OPTS]
bllen_min=0.0
bllen_max=250.0
bl_ew_min=0.0
ex_ants="46,47,40,54,55,41,53,49,48"

[WorkFlow]
actions = ["DPSS_CALIBRATE"]

[DPSS_CALIBRATE]
chunk_size=8
stride_length=8
mem = 64000
args = ["${DELAY_OPTS:horizon}", "${DELAY_OPTS:offset}", "${DELAY_OPTS:min_dly}", "${SELECT_OPTS:bllen_min}",
        "${SELECT_OPTS:bllen_max}", "${SELECT_OPTS:bl_ew_min}", "${SELECT_OPTS:ex_ants}", "{obsid_list}"]
