[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/aewallwi/hera_pipelines/pipelines/calamity/dpss_calibrate/task_scripts"
base_mem = 256000
base_cpu = 16
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"
conda_env = "hera3gpu"
source_script = "~/.bashrc"
gres = "gpu"
batch_system = "pbs"
label="hex2"
tol=1e-16
precision=64

[DELAY_OPTS]
horizon=1.0
offset=1.33333333333
min_dly=100.0
model_regularization="pos_hoc"

[SELECT_OPTS]
bllen_min=0.0
bllen_max=250.0
bl_ew_min=0.0
ex_ants="none"
select_ants="93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127"
[WorkFlow]
actions = ["DPSS_CALIBRATE_NRAO_GPU_NODE"]

[DPSS_CALIBRATE_NRAO_GPU_NODE]
chunk_size=2
stride_length=2
mem = 256000
args = ["${DELAY_OPTS:horizon}", "${DELAY_OPTS:offset}", "${DELAY_OPTS:min_dly}", "${SELECT_OPTS:bllen_min}",
        "${SELECT_OPTS:bllen_max}", "${SELECT_OPTS:bl_ew_min}", "${DELAY_OPTS:model_regularization}",
        "${SELECT_OPTS:ex_ants}", "${SELECT_OPTS:select_ants}", "${Options:label}", "${Options:tol}", "${Options:precision}", "{obsid_list}"]
extra_batch_options = "-l feature=gpu"
