[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/calamity/lstbin/task_scripts/"
source_script = "~/.bashrc"
conda_env = "hera3"
base_mem = 16000
base_cpu = 1
timeout = "48h"
mail_user = "aewallwi+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "False"
Nbls_to_load = 50
sigma = 5
min_N = 1
rephase = "True"
ntimes_per_file = 2
dlst = 0.001090830782
lst_start = 6.2190 # this is before the first LST on 2459114 and after the last LST on 2459139
#lst_start =
fixed_lst_start = "True"
vis_units = "Jy"
parallelize = "True"
average_redundant_baselines = "False"
file_ext = "{type}.{time:7.5f}.uvh5"
outdir = "/lustre/aoc/projects/hera/aewallwi/calamity/mwadata/lstbin/all_epochs/"
parent_dir = "/lustre/aoc/projects/hera/aewallwi/calamity/makeflow/lstbin_all_epochs/"
data_files = [
               "/users/aewallwi/lustre/calamity/mwadata/lstbin/epoch_0/zen.LST.*.uvh5",
               "/users/aewallwi/lustre/calamity/mwadata/lstbin/epoch_1/zen.LST.*.uvh5",
               "/users/aewallwi/lustre/calamity/mwadata/lstbin/epoch_2/zen.LST.*.uvh5",
              ]
calibration = "''"
flag_thresh = 0.8


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "flag_thresh", "average_redundant_baselines"]
