[Options]
makeflow_type = "analysis"
source_script = "~/.bashrc"
base_mem = 15500
base_cpu = 1
timeout = "24h"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/src/hera_pipelines/pipelines/h6c/idr3/v1/post-lstbin/task_scripts"
conda_env = "h6c_idr3"
batch_system = "slurm"

[NOTEBOOK_OPTS]
toml_file = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/makeflow-pspec/h6c_pspec_14band.toml"  # this file
toml_section = "CONFIG_OPTS"
kernel = ""
nb_output_repo = '/lustre/aoc/projects/hera/h6c-analysis/IDR3/notebooks'

[CONFIG_OPTS] # This section is directly read when running the notebook.
# General Options
PLOT = true
SAVE_RESULTS = true

# Spectral Options
BAND_STR = "50.1~62.2,63.3~73.5,74.6~85.4,108.0~116.1,117.3~124.4,125.3~136.2,138.3~148.2,150.1~159.2,159.3~169.9,171.9~181.1,181.4~196.4,198.5~208.4,212.3~220.6,224.4~231.1"  # MHz
ALREADY_INPAINTED = true
PERFORM_INPAINT = false
INPAINT_MIN_DLY = 500.0  # ns
INPAINT_HORIZON = 1.0
INPAINT_STANDOFF = 0.0
INPAINT_EIGENVAL_CUTOFF = 1e-12

PERFORM_DLY_FILT = false
DLY_FILT_MIN_DLY = 150.0  # ns
DLY_FILT_HORIZON = 1.0
DLY_FILT_STANDOFF = 0.0
DLY_FILT_EIGENVAL_CUTOFF = 1e-12

USE_BAND_AVG_NSAMPLES = true
FM_CUT_FREQ = 100000000.0  # Hz
PIXEL_FLAG_CUT = 0.0
CHANNEL_FLAG_CUT = 0.0

# Temporal options
INTEGRATION_FLAG_CUT = 0.2
NINTERLEAVE = 4
XTALK_FR = 0.01  # mHz
FR_SPECTRA_FILE = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/beam_simulation_products/spectra_cache_hera_core.h5"
FR_QUANTILE_LOW = 0.05
FR_QUANTILE_HIGH = 0.95
FR_EIGENVAL_CUTOFF = 1e-12
TARGET_AVERAGING_TIME = 300  # seconds

LST_MIN = 1.25  # 30 minutes inside H1C, because FRF's bleed structure (galaxy and pulsars)
LST_MAX = 5.75

# pspec options
EFIELD_HEALPIX_BEAM_FILE = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/beam_simulation_products/NF_HERA_Vivaldi_efield_beam_healpix.fits"
TAPER = "bh"
INCLUDE_INTERLEAVE_AUTO_PS = false
STORE_WINDOW_FUNCTIONS = true

[WorkFlow]
actions = [
    "SINGLE_BASELINE_POSTPROCESSING_AND_PSPEC",
    "MERGE_SINGLE_BASELINE_FILES",
]

[SINGLE_BASELINE_POSTPROCESSING_AND_PSPEC]
args = [
    "{basename}",
    "${NOTEBOOK_OPTS:toml_file}",
    "${NOTEBOOK_OPTS:toml_section}",
    "${Options:conda_env}",
    "${NOTEBOOK_OPTS:nb_output_repo}",   
]

[MERGE_SINGLE_BASELINE_FILES]
prereqs = [
    "SINGLE_BASELINE_POSTPROCESSING_AND_PSPEC",
]
chunk_size = 1
stride_length = "all"
time_centered = false
args = [
    "{basename}",
]
mem=250000
