[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v3/lstbin/task_scripts/"
source_script = "~/.bashrc"
conda_env = "hera3dev"
base_mem = 8000
base_cpu = 1
timeout = "48h"
mail_user = "aewallwi+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "False"
Nbls_to_load = 50
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 15
dlst = 0.0007046864745507975
lst_start = 5.178260914725223 # this is before the first LST on 2459118 and after the last LST on 2459139
fixed_lst_start = "True"
vis_units = "Jy"
parallelize = "True"
average_redundant_baselines = "False"
file_ext = "grp1.of2.{type}.{time:7.5f}.diff.low-band-allbls.autos.foreground_filled.uvh5"
outdir = "/lustre/aoc/projects/hera/H4C/lstbin/after_filtering_before_red_averaging/low-band/"
parent_dir = "/lustre/aoc/projects/hera/H4C/makeflow/lstbin_after_filtering_before_red_averaging_autos_diff"
data_files = ["/lustre/aoc/projects/hera/H4C/postprocessing/2459118/zen.*.diff.low-band-allbls.autos.foreground_filled.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459119/zen.*.diff.low-band-allbls.autos.foreground_filled.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459120/zen.*.diff.low-band-allbls.autos.foreground_filled.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459121/zen.*.diff.low-band-allbls.autos.foreground_filled.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459122/zen.*.diff.low-band-allbls.autos.foreground_filled.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459139/zen.*.diff.low-band-allbls.autos.foreground_filled.uvh5",
              ]
calibration = "''"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags/"
flag_thresh = 0.8


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "flag_thresh", "average_redundant_baselines", "yaml_dir", "calibration"]
