# This is the lstbin TOML file for the redavg-smoothcal-inpaint-1000ns case.

[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/src/hera_pipelines/pipelines/h6c/idr3/v1/lstbin/task_scripts/"
source_script = "~/.bashrc"
conda_env = "h6c_idr3"
base_mem = 24000
base_cpu = 1
timeout = "48h"

[LSTBIN_OPTS]                                                                                                                                                                                                                                                                                                                                               
# ---- Parameters used by hera_opm to build the makeflow ----
outdir = "${LSTAVG_OPTS:outdir}"
bl_chunk_size = 2000
parallelize = true

[FILE_CFG]
# This section specifies a file configuration for LST-binning.
# The possible parameters here any input attribute of the
# LSTBinConfiguration class in hera_cal.lst_stack.config.
# The 'datafiles' section can contain any parameter that is
# passed to the `.find_datafiles()` method of that class.
nlsts_per_file = 2
lst_start = 0.0
antpairs_from_last_file_each_night = true
where_inpainted_file_rules = [[".inpainted.FR0_filtered.uvh5", ".where_inpainted.h5"]]

[FILE_CFG.datafiles]                                                                                                                                                                 
# Arguments to specify input files.
# Files to be read will be:
#    {datadir}/{nightdir}/zen.{jdglob}.{sd}.{label}[.]{extension}
datadir="/lustre/aoc/projects/hera/h6c-analysis/IDR3/"
nights=[
  "2459861", "2459862", "2459863", "2459864", "2459866", 
  "2459867", "2459868", "2459869", "2459870", "2459871", 
  "2459872", "2459873", "2459874", "2459876"
]
fileglob = "{night}/zen.{night}.?????.sum.smooth_calibrated.red_avg.inpainted.FR0_filtered.uvh5"

[LSTAVG_OPTS]
# Options for the notebook running -- i.e. the metrics and averaging.
outdir = "/lustre/aoc/projects/hera/h6c-analysis/IDR3/lstbin-outputs/redavg-smoothcal-inpaint-1000ns-FR0filt/"
bl_chunk_size = "${LSTBIN_OPTS:bl_chunk_size}"
fname_format = "{inpaint_mode}/zen.{kind}.{lst:7.5f}.{blchunk}.sum.uvh5"
overwrite = true
write_med_mad = false
plot_every = 180  # about 1 hour
save_metric_data = true
save_lstbin_data = true
do_extra_flagging = false
do_lstcal = true
inpaint_method = "pre-inpainted"
smoothing_scale = 30e6

# ========================================= THE WORKFLOW ========================
[WorkFlow]
actions = ["PER_OUTFILE_LSTSTACK_METRICS_NOTEBOOK"]

[PER_OUTFILE_LSTSTACK_METRICS_NOTEBOOK]
args = [
  "outdir", "lstconf", "lstavg_toml_file", "output_file_select", "kernel", "output_blchnk_select"
]
