# This is a file for running quick tests of the LST binner when things are updated.

[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR2/src/hera_pipelines/pipelines/h6c/idr2/v2/lstbin/task_scripts"
source_script = "~/.bashrc"
conda_env = "h6c"
base_mem = 8000
base_cpu = 1
timeout = "48h"
mail_user = "steven.g.murray@asu.edu"

[LSTBIN_OPTS]
Nbls_to_load=5000
rephase = "True"
ntimes_per_file = 2
lst_start = 0.0
# lst_width = // default if not provided is 2pi
vis_units = "Jy"
parallelize = "True"
average_redundant_baselines = "False"
fname_format = "{inpaint_mode}/zen.{kind}.{lst:7.5f}.sum.uvh5"
outdir = "/lustre/aoc/projects/hera/h6c-analysis/IDR2/lstbin-outputs/redavg-smoothcal/"

# Write out full data every hour
golden_lsts = "0.0123324,0.27413179,0.53593118,0.79773057,1.05952996,1.32132934,1.58312873,1.84492812,2.10672751,2.36852689,2.63032628,2.89212567,3.15392506,3.41572445,3.67752383,3.93932322,4.20112261,4.462922,4.72472138,4.98652077,5.24832016,5.51011955,5.77191894,6.03371832"

save_channels = "150,750,1250"
parent_dir = "/lustre/aoc/projects/hera/h6c-analysis/IDR2/makeflow-lstbin/redavg-smoothcal/"
profile_funcs = "hera_cal.io:HERAData.read,hera_cal.io:get_blt_slices,hera_cal.io:HERAData.build_datacontainers,pyuvdata.uvdata:UVData.read,pyuvdata.uvdata:UVData.read_uvh5,pyuvdata.uvdata.uvh5,hera_cal.lstbin_simple"
blts_are_rectangular=true
time_axis_faster_than_bls=true
only_last_file_per_night="True"
freq_min="None"
freq_max="None"
overwrite="True"

# The data files that go into the lstbin are defined as
#   zen.*.{sd}.{label}[.]{extension}
# where the sd, label and extension are defined below.
# The where_inpainted_file_extension replaces the {sd}.{label}[.]{extension}
# to specify the inpainting flag files.
where_inpainted_file_extension=".where_inpainted.h5"
sigma_clip_in_inpainted_mode="False"
write_med_mad="True"

# SIGMA CLIPPING
# Number of sigma away from the median before we clip.
sigma_clip_thresh = "none"
# Minimum number of data points before we clip
sigma_clip_min_N = 4

# Make calibration 'none' to not use any calibration.
calibration = "none"
flag_thresh = 0.8
yaml_dir = "none"
ignore_missing_calfiles="True"

# Arguments to specify input files. Note that hera_opm picks up on these
# when *building* the makeflow, i.e. they're not just used when running the do-script.
# Files to be read will be "{datadir}/{nightdir}/zen.*.{sd}.{label}[.]{extension}"
# If "data_files" is provided, it should be a list of glob patterns specifying all
# files. In that case, none of the other arguments will be used.
# top-level directory in which all the data live.
datadir="/lustre/aoc/projects/hera/h6c-analysis/IDR2/"

# Directories inside 'datadir' that hold the data for each night.
nightdirs = [
  "2459861", "2459862", "2459863", "2459864", 
#  "2459865", 
  "2459866", "2459867", "2459868", "2459869",
  "2459870", "2459871", "2459872", "2459873", "2459874",
#  "2459875",
  "2459876",
]

# The extension of the files to be LST-binned. 
extension = "smooth_calibrated.red_avg.inpaint.uvh5"

# The label applied by previous steps to the data files to be read.
# If no label, leave empty (the following dot will be elided).
label = ""

# Whether to LST-bin sum or diff files.
sd = "sum"

# glob to use for JD's inside each night.
jdglob = "*"


# ========================================= THE WORKFLOW ========================
[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
# Note that 'label' has to be last since it can be empty...
args = [
  "rephase", "vis_units", "output_file_select", "fname_format",
  "outdir", "Nbls_to_load", "yaml_dir", "calibration", "ignore_missing_calfiles",
   "profile_funcs", "save_channels", "golden_lsts",
   "sigma_clip_thresh", "sigma_clip_min_N",
   "only_last_file_per_night", "freq_min", "freq_max",
   "where_inpainted_file_extension", "sd", "extension",
   "sigma_clip_in_inpainted_mode", "write_med_mad", "label"
]
