[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/H1C_IDR3/IDR3_3/h1c_idr3_software/hera_pipelines/pipelines/h1c/idr3/v3/task_scripts"
path_to_a_priori_flags = "/lustre/aoc/projects/hera/H1C_IDR3/IDR3_3/h1c_idr3_software/hera_pipelines/pipelines/h1c/idr3/v3/a_priori_flags"
conda_env = "h1c_idr3_3"
source_script = "~/.bashrc"
base_mem = 8000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "jsdillon+nrao@berkeley.edu"

[NOTEBOOK_OPTS]
nb_template_dir = '/lustre/aoc/projects/hera/H1C_IDR3/IDR3_3/h1c_idr3_software/hera_notebook_templates/notebooks'
nb_output_repo = '/lustre/aoc/projects/hera/H1C_IDR3/IDR3_3/H1C_IDR3_3_Notebooks'
git_push = false

[REDCAL_OPTS]
ant_z_thresh = 1e100
solar_horizon = 0.0
nInt_to_load = 10
flag_nchan_low = 50
flag_nchan_high = 50
oc_maxiter = 10000
min_bl_cut = 15
max_bl_cut = 90
max_dims = 2
fc_min_vis_per_ant = 16
check_every = 50
check_after = 500

[ABSCAL_OPTS]
model_files_glob = "'/lustre/aoc/projects/hera/H1C_IDR3/abscal_model/zen.245804*.HH.uvRXLS.uvh5'"
nInt_to_load = 6
min_bl_cut = 1.0
max_bl_cut = 140.0
phs_max_iter = 100
phs_conv_crit = 1e-6
edge_cut = 100

[XRFI_OPTS]
kt_size = 10
kf_size = 10
sig_init = 5.0
sig_adj = 2.0
Nwf_per_load = 100
# TODO: investigate dumping autos and/or omni vis

[XRFI_DAY_THRESHOLD_OPTS]
nsig_f = 7.0
nsig_t = 7.0
nsig_f_adj = 3.0
nsig_t_adj = 3.0

[CAL_SMOOTH_OPTS] # TODO: update to DPSS
freq_scale = 10
time_scale = 21600
tol = 1e-6
filter_mode = "rect"
window = "tukey"
maxiter = 100
alpha = 0.3
freq_threshold = 1.0
time_threshold = 1.0
ant_threshold = 0.5
lst_blacklists = ""

############################################################################################################

[WorkFlow]
actions = ["MAKE_DOWNSELCTED_UVH5", 
           "REDCAL",
           "REDCAL_INSPECT_NOTEBOOK",
           "ABSCAL",
           "ABSCAL_INSPECT_NOTEBOOK",
           "XRFI",
           "XRFI_DAY_THRESHOLD",
           "RFI_INSPECT_NOTEBOOK",
           "CAL_SMOOTH",
           "SMOOTH_CAL_INSPECT_NOTEBOOK",
           # "CLEAN_FILES",
          ]

[MAKE_DOWNSELCTED_UVH5]
mem = 32000
args = ["{basename}",
        "${Options:path_to_a_priori_flags}",
       ]

[REDCAL]
prereqs = "MAKE_DOWNSELCTED_UVH5"
args = ["{basename}",
        "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}",
        "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}",
        "${REDCAL_OPTS:oc_maxiter}",
        "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}",
        "${REDCAL_OPTS:max_bl_cut}",
        "${REDCAL_OPTS:max_dims}",
        "${REDCAL_OPTS:fc_min_vis_per_ant}",
        "${REDCAL_OPTS:check_every}",
        "${REDCAL_OPTS:check_after}",
       ]

[REDCAL_INSPECT_NOTEBOOK]
prereqs = "REDCAL"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
       ]

[ABSCAL]
prereqs = "REDCAL"
args = ["{basename}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${ABSCAL_OPTS:nInt_to_load}",
        "${ABSCAL_OPTS:min_bl_cut}",
        "${ABSCAL_OPTS:max_bl_cut}",
        "${ABSCAL_OPTS:phs_max_iter}",
        "${ABSCAL_OPTS:phs_conv_crit}",
        "${ABSCAL_OPTS:edge_cut}"
       ]

[ABSCAL_INSPECT_NOTEBOOK]
prereqs = "ABSCAL"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}",
       ]

[XRFI]
prereqs = ["REDCAL",
           "ABSCAL",
          ]
args = ["${XRFI_OPTS:kt_size}",
        "${XRFI_OPTS:kf_size}",
        "${XRFI_OPTS:sig_init}",
        "${XRFI_OPTS:sig_adj}",
        "${Options:path_to_a_priori_flags}",
        "${XRFI_OPTS:Nwf_per_load}",
        "{obsid_list}"
       ]
# xrfi will drop data within kt_size of time edge. Total integrations read in
# must be greater than 2 * kt_size. 
chunk_size = 3
stride_length = 1
time_centered = true
collect_stragglers = true

[XRFI_DAY_THRESHOLD]
prereqs = ["XRFI",
           "ABSCAL",
          ]
prereq_chunk_size = "all"
chunk_size = "all"
stride_length = "all"
time_centered = false
args = ["${XRFI_DAY_THRESHOLD_OPTS:nsig_f}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}",
        "${Options:path_to_a_priori_flags}",
        "{obsid_list}"
       ]

[RFI_INSPECT_NOTEBOOK]
prereqs = "XRFI_DAY_THRESHOLD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        ]

[CAL_SMOOTH]
prereqs = "XRFI_DAY_THRESHOLD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${CAL_SMOOTH_OPTS:freq_scale}",
        "${CAL_SMOOTH_OPTS:time_scale}",
        "${CAL_SMOOTH_OPTS:tol}",
        "${CAL_SMOOTH_OPTS:filter_mode}",
        "${CAL_SMOOTH_OPTS:window}",
        "${CAL_SMOOTH_OPTS:maxiter}",
        "${CAL_SMOOTH_OPTS:alpha}",
        "${CAL_SMOOTH_OPTS:freq_threshold}",
        "${CAL_SMOOTH_OPTS:time_threshold}",
        "${CAL_SMOOTH_OPTS:ant_threshold}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}"
       ]

[SMOOTH_CAL_INSPECT_NOTEBOOK]
prereqs = "CAL_SMOOTH"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}",
       ]

[CLEAN_FILES]
prereqs = ["REDCAL_INSPECT_NOTEBOOK",
           "ABSCAL_INSPECT_NOTEBOOK",
           "SMOOTH_CAL_INSPECT_NOTEBOOK",
           "RFI_INSPECT_NOTEBOOK",
          ]
prereq_chunk_size = "all"
args = ["{basename}"]

