[Options]
makeflow_type = "analysis"
source_script = "~/.bashrc"
base_mem = 12000 # TODO: Check if this is the right number for site
base_cpu = 1
timeout = "24h"
path_to_do_scripts = "/home/obs/src/hera_pipelines/pipelines/h4c/rtp/v1/stage_1_task_scripts"
conda_env = "RTP"
mandc_report = true
batch_system = "slurm"
default_queue = "hera,bigmem"

[LIBRARIAN_OPTS]
# These trigger which sets of files get added to the librarian
upload_to_librarian = true # upload raw data to librarian, if false all below switches will be ignored.
librarian_auto_metrics = true

[NOTEBOOK_OPTS]
nb_template_dir = '/home/obs/src/hera_notebook_templates/notebooks'
nb_output_repo = '/home/obs/src/H4C_Notebooks'
git_push = true

[AUTO_METRICS_OPTS]
median_round_modz_cut = 16.0
mean_round_modz_cut = 8.0
edge_cut = 100
chan_thresh_frac = 0.05

[XRFI_OPTS]
kt_size = 8
kf_size = 8
sig_init = 5.0
sig_adj = 2.0


############################################################################################################

[WorkFlow]
actions = ["SETUP",
           "AUTO_METRICS",
           "AUTO_METRICS_INSPECT_NOTEBOOK",
          ]

[SETUP]
args = []

[AUTO_METRICS]
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "{AUTO_METRICS_OPTS:median_round_modz_cut}",
        "{AUTO_METRICS_OPTS:mean_round_modz_cut}",
        "{AUTO_METRICS_OPTS:edge_cut}",
        "${XRFI_OPTS:kt_size}",
        "${XRFI_OPTS:kf_size}",
        "${XRFI_OPTS:sig_init}",
        "${XRFI_OPTS:sig_adj}",
        "{AUTO_METRICS_OPTS:chan_thresh_frac}", 
        "${LIBRARIAN_OPTS:upload_to_librarian}",
        "${LIBRARIAN_OPTS:librarian_auto_metrics}",
        ]

[AUTO_METRICS_INSPECT_NOTEBOOK]
prereqs = "AUTO_METRICS"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        ]
