[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v3/pre_lstbin/task_scripts"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 8000
base_cpu = 1
timeout = "24h"
mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 15 # this number is to make sure that the branch cut does not occur inside of a single file.
                # should be adjusted depending on where the cut is.
spw0 = 150
spw1 = 320
label = "low-band-allbls-battletest"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags/"
nbl_per_load = 100
t_avg = 300.0
grpstr = "grp1.of2"


[DELAY_OPTS]
tol = 1e-9
standoff = 100
min_dly = 1000
calibration = "none"
filter_mode = "DPSS"
# we may want to consider another flagging round after delay filtering.

[FR_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.025
tol = 1e-9
# inpaint beyond frate limit by this much.
frate_standoff = 0.0
min_frate = 0.5


############################################################################################################

[WorkFlow]
actions = ["PRE_CHUNK",
           "DELAY",
           "XTALK",
           "TIME_INPAINT",
           "RECONSTITUTE",
           "CLEANUP"]

[PRE_CHUNK]
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}",
     "${Options:chunk_size}",
     "${Options:spw0}", "${Options:spw1}", "${Options:yaml_dir}"]

[DELAY]
prereqs = "PRE_CHUNK"
prereq_chunk_size = 1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}", "${DELAY_OPTS:tol}",
        "${DELAY_OPTS:standoff}",   "${DELAY_OPTS:min_dly}", , "${Options:cache_dir}",
        "${DELAY_OPTS:filter_mode}",
        "${Options:nbl_per_load}"]

[XTALK]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}", "${FR_OPTS:tol}",
        "${FR_OPTS:frmax0}", "${FR_OPTS:frmax1}",
        "${Options:cache_dir}"]


[TIME_INPAINT]
prereqs = "XTALK"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}", "${FR_OPTS:tol}",
        "${FR_OPTS:frate_standoff}", "${FR_OPTS:min_frate}",
        "${Options:cache_dir}"]


[RECONSTITUTE]
prereqs = "TIME_INPAINT"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}"]

[CLEANUP]
prereqs= "RECONSTITUTE"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}"]
