[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v4/pre_lstbin/task_scripts"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 8000
base_cpu = 1
timeout = "24h"
mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 15 # this number is to make sure that the branch cut does not occur inside of a single file.                # should be adjusted depending on where the cut is.
spw0 = 792
spw1 = 1000
label = "high-band-allbls"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags/"
nbl_per_load = 100
t_avg = 300.0
grpstr = "grp1.of2"


[DELAY_OPTS]
tol = 1e-9
standoff = 100
min_dly = 1000
calibration = "none"
filter_mode = "DPSS"
# we may want to consider another flagging round after delay filtering.

[FR_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.025
tol = 1e-9
# inpaint beyond frate limit by this much.
frate_standoff = 0.0
min_frate = 0.5

[PSPEC_OPTS]
pstokes="pI"
beam_file="/lustre/aoc/projects/hera/H4C/beams/NF_HERA_Vivaldi_efield_beam_healpix"
spw_ranges="0~85,85~170"
nsamples=100
seed=10

[FILTERING_NOTEBOOK_OPTS]
nb_template_dir = "/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks/"
nb_output_repo = "/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks/"
git_push = "False"
nreds = 6
max_bls_per_redgrp = 4
nskip = 3

[POWER_SPECTRUM_NOTEBOOK_OPTS]
nb_template_dir = "/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks/"
nb_output_repo = "/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks/"
git_push = "False"
spws = "0,1"
lst_fields="1~3,4.2~6.2"
grp_skip = 10
blp_skip = 2
max_plots_per_row = 10
field_labels = "1,2"

############################################################################################################

[WorkFlow]
actions = ["PRE_CHUNK",
           "DELAY",
           "XTALK",
           "TIME_INPAINT",
           "TIME_AVERAGE",
           "RECONSTITUTE",
           "PSTOKES",
           "PSPEC",
           "AUTOERRORS",
           #BOOTSTRAPERRORS,
           "FILTERING_NOTEBOOK",
           "POWER_SPECTRUM_NOTEBOOK",
           "CLEANUP"]

[PRE_CHUNK]
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}",
    "${Options:chunk_size}",
    "${Options:spw0}", "${Options:spw1}", "${Options:yaml_dir}"]

[DELAY]
prereqs = "PRE_CHUNK"
prereq_chunk_size = 1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
       "${Options:label}", "${DELAY_OPTS:tol}",
       "${DELAY_OPTS:standoff}",   "${DELAY_OPTS:min_dly}", , "${Options:cache_dir}",
       "${DELAY_OPTS:filter_mode}",
       "${Options:nbl_per_load}"]

[XTALK]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
       "${Options:label}", "${FR_OPTS:tol}",
       "${FR_OPTS:frmax0}", "${FR_OPTS:frmax1}",
       "${Options:cache_dir}"]


[TIME_INPAINT]
prereqs = "XTALK"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
       "${Options:label}", "${FR_OPTS:tol}",
       "${FR_OPTS:frate_standoff}", "${FR_OPTS:min_frate}",
       "${Options:cache_dir}"]


[TIME_AVERAGE]
prereqs = "TIME_INPAINT"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
       "${Options:label}", "${Options:t_avg}"]

[RECONSTITUTE]
prereqs = "TIME_AVERAGE"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
       "${Options:label}"]

[PSTOKES]
prereqs="RECONSTITUTE"
prereq_chunk_size=1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}",
     "${Options:label}", "${PSPEC_OPTS:pstokes}"]

[PSPEC]
prereqs = "PSTOKES"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}",
     "${PSPEC_OPTS:beam_file}", "${PSPEC_OPTS:spw_ranges}",
     "${PSPEC_OPTS:pol_pairs}"]

[AUTOERRORS]
prereqs = "PSPEC"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}", "${PSPEC_OPTS:beam_file}"]

[BOOTSTRAPERRORS]
prereqs = "AUTOERRORS"
prereq_chunk_size = 1
mem=24000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}", "${PSPEC_OPTS:nsamples}", "${PSPEC_OPTS:seed}"]

[FILTERING_NOTEBOOK]
prereqs="AUTOERRORS"
prereq_chunk_size="all"
mem=128000
chunk_size=1
stride_length="all"
time_centered = false
args=["{basename}", "${FILTERING_NOTEBOOK_OPTS:nb_template_dir}", "${FILTERING_NOTEBOOK_OPTS:nb_output_repo}",
      "${FILTERING_NOTEBOOK_OPTS:git_push}", "${Options:label}", "${FILTERING_NOTEBOOK_OPTS:nreds}",
      "${FILTERING_NOTEBOOK_OPTS:max_bls_per_redgrp}", "${FILTERING_NOTEBOOK_OPTS:nskip}"]

[POWER_SPECTRUM_NOTEBOOK]
prereqs="AUTOERRORS"
prereq_chunk_size="all"
mem=128000
chunk_size=1
stride_length="all"
time_centered = false
args=["{basename}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:nb_template_dir}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:nb_output_repo}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:git_push}", "${Options:label}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:spws}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:lst_fields}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:grp_skip}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:blp_skip}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:field_labels}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:max_plots_per_row}"]

[CLEANUP]
prereqs= "POWER_SPECTRUM_NOTEBOOK"
prereq_chunk_size = "all"
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}"]
