[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v6/lstbin/task_scripts/"
source_script = "~/.bashrc"
conda_env = "hera3dev"
base_mem = 16000
base_cpu = 1
timeout = "48h"
mail_user = "aewallwi+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "False"
Nbls_to_load = 50
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 2
dlst = 0.0007046864745507975
lst_start = 5.17301381 # this is before the first LST on 2459114 and after the last LST on 2459139
fixed_lst_start = "False"
vis_units = "Jy"
parallelize = "True"
average_redundant_baselines = "False"
file_ext = "{type}.{time:7.5f}.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5"
outdir = "/lustre/aoc/projects/hera/H4C/lstbin/after_filtering_before_red_averaging/all-bands-long-delay-clean-include-variable-ants/"
parent_dir = "/lustre/aoc/projects/hera/H4C/makeflow/lstbin_diff_h4c_idr2p2"
data_files = [
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459114/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459116/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459118/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459119/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459120/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459121/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459122/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459123/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459125/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459126/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459127/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459128/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459130/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459132/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459133/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459134/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459135/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459136/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459137/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459138/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459139/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459140/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              "/lustre/aoc/projects/hera/H4C/postprocessing/2459141/zen.*.diff.all-bands-allbls-long-delay-clean-include-variable-ants.foreground_filled.xtalk_filtered.uvh5",
              ]
calibration = "''"
flag_thresh = 0.8
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v6/pre_lstbin/flag_yamls/stage_2_a_priori_flags_include_variable_with_expanded_flags/"


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "flag_thresh", "average_redundant_baselines", "yaml_dir", "calibration"]
