[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/lustre/aoc/projects/hera/Validation/test-4.1.0/software/hera_pipelines/pipelines/validation/h1c_idr3_2/abscal_model_scripts"
path_to_a_priori_flags = "/lustre/aoc/projects/hera/H1C_IDR3/IDR3_2/h1c_idr3_software/hera_pipelines/pipelines/h1c/idr3/v2/a_priori_flags"
conda_env = "h1c_idr3_2_validation"
source_script = "~/.bashrc"
base_mem = 24000
base_cpu = 1
timeout = "24h"

[BUILD_MODEL_OPTS]
sky_cmp = "foreground"
save_dir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/abscal_model"

[DELAY_FILTER_MODEL_OPTS]
tol = 0.0000001
gain = 0.9
skip_wgt = 0.2
edgecut_low = 50
edgecut_hi = 50
maxiter = 100
min_dly = 150
horizon = 1.0
standoff = 50
window = 'tukey'
alpha = 0.2

############################################################################################################

[WorkFlow]
actions = ["BUILD_MODEL",
           "DELAY_FILTER_MODEL",
          ]

[BUILD_MODEL]
args = ["{basename}",
        "${BUILD_MODEL_OPTS:sky_cmp}",
        "${BUILD_MODEL_OPTS:save_dir}",
       ]

[DELAY_FILTER_MODEL]
prereqs = "BUILD_MODEL"
args = ["{basename}",
        "${DELAY_FILTER_MODEL_OPTS:horizon}",
        "${DELAY_FILTER_MODEL_OPTS:standoff}",
        "${DELAY_FILTER_MODEL_OPTS:min_dly}",
        "${DELAY_FILTER_MODEL_OPTS:gain}",
        "${DELAY_FILTER_MODEL_OPTS:maxiter}",
        "${DELAY_FILTER_MODEL_OPTS:window}",
        "${DELAY_FILTER_MODEL_OPTS:alpha}",
        "${DELAY_FILTER_MODEL_OPTS:edgecut_low}",
        "${DELAY_FILTER_MODEL_OPTS:edgecut_hi}",
        "${DELAY_FILTER_MODEL_OPTS:tol}",
        "${DELAY_FILTER_MODEL_OPTS:skip_wgt}",
       ]
