[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/lustre/aoc/projects/hera/Validation/test-4.1.0/software/hera_pipelines/pipelines/validation/h1c_idr3_2/task_scripts"
source_script = "~/.bashrc"
conda_env = "h1c_idr3_2_validation"
base_mem = 80000
base_cpu = 4
timeout = "48h"
pbs_mail_user = "jsdillon+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "True"
Nbls_to_load = 100
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 60
dlst = 0.001565970008
lst_start = 4.711094445 # this is before the first LST on 2458041 and after the last LST on 2458208
fixed_lst_start = "True"
vis_units = "Jy"
parallelize = "True"
file_ext = "grp1.of1.{type}.{time:7.5f}.sum.uvh5"
outdir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/LSTBIN/epoch_2"
parent_dir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/LSTBIN/epoch_2"
data_files = ["/lustre/aoc/projects/hera/Validation/test-4.1.0/2458134/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458135/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458136/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458139/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458141/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458142/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458143/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458144/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458145/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458146/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458147/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458148/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458149/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458150/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458151/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458153/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458154/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458155/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458157/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458158/zen.*.sum.smooth_calibrated.uvh5"]
calibration = "''"


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "fixed_lst_start", "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "calibration"]
