[Options]
makeflow_type = "lstbin"
path_to_do_scripts = "/lustre/aoc/projects/hera/Validation/test-4.1.0/software/hera_pipelines/pipelines/validation/h1c_idr3_2/task_scripts"
source_script = "~/.bashrc"
conda_env = "h1c_idr3_2_validation_lstbin"
base_mem = 60000
base_cpu = 1
timeout = "48h"
pbs_mail_user = "jsdillon+nrao@berkeley.edu"

[LSTBIN_OPTS]
sig_clip = "True"
Nbls_to_load = 100
sigma = 5
min_N = 5
rephase = "True"
ntimes_per_file = 60
dlst = 0.001565970008
lst_start = 4.711094445 # this is before the first LST on 2458041 and after the last LST on 2458208
vis_units = "Jy"
parallelize = "True"
file_ext = "grp1.of1.{type}.{time:7.5f}.sum.uvh5"
outdir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/LSTBIN/epoch_1"
parent_dir = "/lustre/aoc/projects/hera/Validation/test-4.1.0/LSTBIN/epoch_1"
data_files = ["/lustre/aoc/projects/hera/Validation/test-4.1.0/2458081/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458083/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458084/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458085/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458086/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458087/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458088/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458090/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458091/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458092/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458094/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458095/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458096/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458097/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458098/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458099/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458101/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458102/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458103/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458104/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458105/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458106/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458107/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458108/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458109/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458110/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458111/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458112/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458113/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458114/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458115/zen.*.sum.smooth_calibrated.uvh5",
              "/lustre/aoc/projects/hera/Validation/test-4.1.0/2458116/zen.*.sum.smooth_calibrated.uvh5"]
calibration = "''"


[WorkFlow]
actions = ["LSTBIN"]

[LSTBIN]
args = ["sig_clip", "sigma", "min_N", "rephase", "ntimes_per_file", "lst_start",
        "dlst", "vis_units", "output_file_select", "file_ext",
        "outdir", "Nbls_to_load", "calibration"]
