[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v2/post_lstbin_pre_inpainting/task_scripts/"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 8000
base_cpu = 1
timeout = "24h"
mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 15 # this number is to make sure that the branch cut does not occur inside of a single file.
                # should be adjusted depending on where the cut is.
spw0 = 150
spw1 = 320
label = "low-band"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags/"
flag_ext="og_flags1"
time_threshold = 0.02
nbl_per_load = 100
t_avg = 300.0
grpstr = "grp1.of1"


[DELAY_OPTS]
tol = 1e-9
standoff = 100
min_dly = 1000
calibration = "none"
filter_mode = "DPSS"
# we may want to consider another flagging round after delay filtering.

[XTALK_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.025
tol = 1e-9
# inpaint beyond frate limit by this much.
frate_standoff = 1.0

[PSPEC_OPTS]
pstokes="pI"
beam_file="/lustre/aoc/projects/hera/aewallwi/HERA-Beams/NicolasFagnoniBeams/NF_HERA_Vivaldi_efield_beam_healpix.fits"
pol_pairs="XX~XX,YY~YY,pI~pI"
spw_ranges="0~85,85~150"
nsamples=100
seed=10


############################################################################################################

[WorkFlow]
actions = ["PRE_CHUNK",
           "DELAY",
           "XTALK",
           "TIME_AVERAGE",
           "RECONSTITUTE",
           "PSTOKES",
           "PSPEC",
           "AUTOERRORS",
           "BOOTSTRAPERRORS",
           "CLEANUP"]

[PRE_CHUNK]
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}",
     "${Options:chunk_size}",
     "${Options:spw0}", "${Options:spw1}", "${Options:grpstr}"]

[DELAY]
prereqs = "PRE_CHUNK"
prereq_chunk_size = 1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}", "${DELAY_OPTS:tol}",
        "${DELAY_OPTS:standoff}",   "${DELAY_OPTS:min_dly}", , "${Options:cache_dir}",
        "${DELAY_OPTS:filter_mode}",
        "${Options:grpstr}", "${Options:nbl_per_load}"]

[XTALK]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}", "${XTALK_OPTS:tol}",
        "${XTALK_OPTS:frmax0}", "${XTALK_OPTS:frmax1}",
        "${XTALK_OPTS:frate_standoff}", "${Options:cache_dir}",
        "${Options:grpstr}"]

[TIME_AVERAGE]
prereqs= "XTALK"
prereq_chunk_size=1
chunk_size=1
stride_length="${Options:chunk_size}"
mem=8000
args=["{basename}",
      "${Options:label}",
      "${Options:t_avg}",
      "${Options:grpstr}"]#, "${Options:n_avg}"]


[RECONSTITUTE]
prereqs = "TIME_AVERAGE"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 8000
args = ["{basename}",
        "${Options:label}", "${Options:grpstr}"]

[PSTOKES]
prereqs="RECONSTITUTE"
prereq_chunk_size=1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:grpstr}",
      "${Options:label}", "${PSPEC_OPTS:pstokes}"]

[PSPEC]
prereqs = "PSTOKES"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}",
      "${Options:grpstr}",
      "${PSPEC_OPTS:beam_file}", "${PSPEC_OPTS:spw_ranges}",
      "${PSPEC_OPTS:pol_pairs}"]

[AUTOERRORS]
prereqs = "PSPEC"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}"]


[BOOTSTRAPERRORS]
prereqs = "AUTOERRORS"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}", "${Options:grpstr}", "${PSPEC_OPTS:nsamples}", "${PSPEC_OPTS:seed}"]


[CLEANUP]
prereqs= "BOOTSTRAPERRORS"
prereq_chunk_size = 1
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}", "${Options:grpstr}"]
