[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v7_interleave/post_lstbin_frate/task_scripts"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 8000
base_cpu = 1
timeout = "24h"
mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 10
spw_ranges='10~105,150~320,515~615,665~717,770~1090'
label = "include-variable-ants-interleave-4-way"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v7_interleave/pre_lstbin/flag_yamls/"
nbl_per_load = 100
t_avg = 300.0
include_diffs = "true"
transfer_filled_flags = "false"
transfer_res_flags = "true"

# we may want to consider another flagging round after delay filtering.

[FR_OPTS]
# dividing this by two for low band.
tol=1e-9
# use this uvbeam object to filter main-lobe.
uvbeam="/lustre/aoc/projects/hera/H4C/beams/NF_HERA_Vivaldi_efield_beam_healpix.fits"
spw_ranges="0~95,95~180,180~265,265~365,365~417,417~497,497~577,577~657,657~737"
percentile_low=5.0
percentile_high=95.0
prefilter_zero_frate="false"
ninterleave=4

[PSPEC_OPTS]
pstokes="pI"
beam_file="/lustre/aoc/projects/hera/H4C/beams/NF_HERA_Vivaldi_efield_beam_healpix"
spw_ranges="0~95,95~180,180~265,265~365,365~417,417~497,497~577,577~657,657~737"
nsamples=100
seed=10

[POWER_SPECTRUM_NOTEBOOK_OPTS]
nb_template_dir = "/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks/"
nb_output_repo = "/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks/"
git_push = "False"
spws = "0,1,2,3,4,5,6,7,8"
lst_fields="1~3,4.2~6.2"
grp_skip = 10
blp_skip = 2
field_labels = "1,2"
max_plots_per_row = 10

############################################################################################################

[WorkFlow]
actions = [
           "PRE_CHUNK",
           "FR_FILTER",
           "TIME_AVERAGE",
           "RECONSTITUTE",
           "PSTOKES",
           "PSPEC",
           "AUTOERRORS"]


[PRE_CHUNK]
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}",
    "${Options:chunk_size}"]

[FR_FILTER]
prereqs = "PRE_CHUNK"
prereq_chunk_size="all"
mem=24000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}",
      "${Options:label}", "${FR_OPTS:tol}", "${FR_OPTS:uvbeam}",
      "${FR_OPTS:percentile_low}", "${FR_OPTS:percentile_high}",
      "${FR_OPTS:spw_ranges}", "${FR_OPTS:prefilter_zero_frate}",
      "${FR_OPTS:ninterleave}"]

[TIME_AVERAGE]
prereqs = "FR_FILTER"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:include_diffs}",
       "${Options:label}", "${Options:t_avg} ${FR_OPTS:ninterleave}"]

[RECONSTITUTE]
prereqs = "TIME_AVERAGE"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:include_diffs}",
       "${Options:label}", "${FR_OPTS:ninterleave}"]

[PSTOKES]
prereqs="RECONSTITUTE"
prereq_chunk_size=1
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}",
     "${Options:label}","${PSPEC_OPTS:pstokes}",
     "${FR_OPTS:ninterleave}"]

[PSPEC]
prereqs = "PSTOKES"
prereq_chunk_size = 1
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}",
     "${PSPEC_OPTS:beam_file}", "${PSPEC_OPTS:spw_ranges}",
     "${FR_OPTS:ninterleave}"]

[AUTOERRORS]
prereqs = "PSPEC"
prereq_chunk_size = 1
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}", "${PSPEC_OPTS:beam_file}"]
