[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/heramgr/hera_software/hera_pipelines/pipelines/validation/h4c/rtp/v2/stage_2_task_scripts"
path_to_a_priori_flags = "/users/heramgr/hera_software/hera_pipelines/pipelines/validation/h4c/rtp/v2/stage_2_a_priori_flags_include_variable"
conda_env = "h4c_validation"
source_script = "~/.bashrc"
base_mem = 16000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "lisaleemcb@gmail.com"

[NOTEBOOK_OPTS]
nb_template_dir = '/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks'
nb_output_repo = '/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks'
git_push = false

[REDCAL_OPTS]
ant_z_thresh = 1e100
solar_horizon = 0.0
nInt_to_load = 10
flag_nchan_low = 0
flag_nchan_high = 0
oc_maxiter = 10000
min_bl_cut = 1 # 15
max_bl_cut = 10000 # 100
max_dims = 4
check_every = 50
check_after = 500

[ABSCAL_OPTS]
model_files_glob = "'/lustre/aoc/projects/hera/zmartino/hera_calib_model/H3C/abscal_files_unique_baselines/zen.2458894.?????.uvh5'"
nInt_to_load = 6
min_bl_cut = 60.0
max_bl_cut = 140.0
phs_max_iter = 100
phs_conv_crit = 1e-6
edge_cut = 100


[XRFI_OPTS]
kt_size = 8
kf_size = 8
sig_init_med = 10.0
sig_adj_med = 4.0
sig_init_mean = 5.0
sig_adj_mean = 2.0
Nwf_per_load = 1000

[XRFI_DAY_THRESHOLD_OPTS]
nsig_f = 7.0
nsig_t = 7.0
nsig_f_adj = 3.0
nsig_t_adj = 3.0

[CAL_SMOOTH_OPTS]
freq_scale = 10
time_scale = 21600
tol = 1e-6
filter_mode = "rect"
window = "tukey"
maxiter = 100
alpha = 0.3
freq_threshold = 1.0
time_threshold = 1.0
ant_threshold = 0.5
lst_blacklists = "0-1.3 2.5-4.3 6.5-9.1 10.6-11.5 11.9-14.3 16.3-1.3"

[APPLY_CAL_REDUNDANT_AVERAGE_OPTS]
nbl_per_load = 1000

[IMAGING_OPTS]
casa = "/home/casa/packages/RHEL7/release/casa-release-5.1.0-68/bin/casa"
casa_imaging_scripts = "/lustre/aoc/projects/hera/H4C/h4c_software/casa_imaging/scripts"
spw = "0:200~280,0:600~700,0:900~1000"
calibration = "smooth_abs.calfits"
ffmpeg = "/users/heramgr/hera_software/ffmpeg-3.4.2-64bit-static/ffmpeg"
framerate = 40
framesize = "1280x720"

############################################################################################################

[WorkFlow]
actions = [
           #"THROW_AWAY_FLAGGED_BASELINES",
           "EXTRACT_AUTOS",
           "REDCAL",
           "REDCAL_INSPECT_NOTEBOOK",
           "ABSCAL",
           "ABSCAL_INSPECT_NOTEBOOK",
           "XRFI",
           #"XRFI_DAY_THRESHOLD",
           "RFI_INSPECT_NOTEBOOK",
           "CAL_SMOOTH",
           "SMOOTH_CAL_INSPECT_NOTEBOOK",
           #"IMAGING",
           #"MOVIES",
           #"APPLY_CAL_REDUNDANT_AVERAGE",
           # "CLEAN_FILES", # TODO: add this back in
          ]

[THROW_AWAY_FLAGGED_BASELINES]
args = ["{basename}", "${Options:path_to_a_priori_flags}"]

[EXTRACT_AUTOS]
#prereqs = "THROW_AWAY_FLAGGED_BASELINES"
args = ["{basename}"]

[REDCAL]
prereqs = "EXTRACT_AUTOS"
prereq_chunk_size = 1
args = ["{basename}",
        "${REDCAL_OPTS:ant_z_thresh}",
        "${REDCAL_OPTS:solar_horizon}",
        "${REDCAL_OPTS:flag_nchan_low}",
        "${REDCAL_OPTS:flag_nchan_high}",
        "${REDCAL_OPTS:oc_maxiter}",
        "${REDCAL_OPTS:nInt_to_load}",
        "${REDCAL_OPTS:min_bl_cut}",
        "${REDCAL_OPTS:max_bl_cut}",
        "${Options:path_to_a_priori_flags}",
        "${REDCAL_OPTS:max_dims}",
        "${REDCAL_OPTS:check_every}",
        "${REDCAL_OPTS:check_after}",
       ]

[REDCAL_INSPECT_NOTEBOOK]
prereqs = "REDCAL"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
       ]

[ABSCAL]
prereqs = "REDCAL"
args = ["{basename}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${ABSCAL_OPTS:nInt_to_load}",
        "${ABSCAL_OPTS:min_bl_cut}",
        "${ABSCAL_OPTS:max_bl_cut}",
        "${ABSCAL_OPTS:phs_max_iter}",
        "${ABSCAL_OPTS:phs_conv_crit}",
        "${ABSCAL_OPTS:edge_cut}"
       ]

[ABSCAL_INSPECT_NOTEBOOK]
prereqs = "ABSCAL"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}",
       ]

[XRFI]
prereqs = ["REDCAL",
          "ABSCAL",
          "EXTRACT_AUTOS",
         ]
args = ["${XRFI_OPTS:kt_size}",
       "${XRFI_OPTS:kf_size}",
       "${XRFI_OPTS:sig_init_med}",
       "${XRFI_OPTS:sig_adj_med}",
       "${XRFI_OPTS:sig_init_mean}",
       "${XRFI_OPTS:sig_adj_mean}",
       "${Options:path_to_a_priori_flags}",
       "${XRFI_OPTS:Nwf_per_load}",
       "{obsid_list}"
      ]
# xrfi will drop data within kt_size of time edge. Total integrations read in
# must be greater than 2 * kt_size.
chunk_size = 31
stride_length = 23
time_centered = true
collect_stragglers = true

[XRFI_DAY_THRESHOLD]
prereqs = ["XRFI",
           "ABSCAL",
          ]
prereq_chunk_size = "all"
chunk_size = "all"
stride_length = "all"
time_centered = false
args = ["${XRFI_DAY_THRESHOLD_OPTS:nsig_f}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_t}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_f_adj}",
        "${XRFI_DAY_THRESHOLD_OPTS:nsig_t_adj}",
        "${Options:path_to_a_priori_flags}",
        "{obsid_list}"
       ]

[RFI_INSPECT_NOTEBOOK]
prereqs = "XRFI"
#prereqs = "XRFI_DAY_THRESHOLD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        ]

[CAL_SMOOTH]
prereqs = "XRFI_DAY_THRESHOLD"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${CAL_SMOOTH_OPTS:freq_scale}",
        "${CAL_SMOOTH_OPTS:time_scale}",
        "${CAL_SMOOTH_OPTS:tol}",
        "${CAL_SMOOTH_OPTS:filter_mode}",
        "${CAL_SMOOTH_OPTS:window}",
        "${CAL_SMOOTH_OPTS:maxiter}",
        "${CAL_SMOOTH_OPTS:alpha}",
        "${CAL_SMOOTH_OPTS:freq_threshold}",
        "${CAL_SMOOTH_OPTS:time_threshold}",
        "${CAL_SMOOTH_OPTS:ant_threshold}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}"
       ]

[SMOOTH_CAL_INSPECT_NOTEBOOK]
prereqs = "CAL_SMOOTH"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${NOTEBOOK_OPTS:nb_output_repo}",
        "${NOTEBOOK_OPTS:git_push}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}",
       ]

[IMAGING]
prereqs = "CAL_SMOOTH"
prereq_chunk_size = "all"
args = ["{basename}",
        "${IMAGING_OPTS:casa}",
        "${IMAGING_OPTS:casa_imaging_scripts}",
        "${IMAGING_OPTS:spw}",
        "${ABSCAL_OPTS:model_files_glob}",
        "${IMAGING_OPTS:calibration}"
       ]

[MOVIES]
prereqs = "IMAGING"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
args = ["{basename}",
        "${IMAGING_OPTS:spw}",
        "${IMAGING_OPTS:ffmpeg}",
        "${IMAGING_OPTS:framerate}",
        "${IMAGING_OPTS:framesize}",
       ]

[APPLY_CAL_REDUNDANT_AVERAGE]
prereqs = "CAL_SMOOTH"
prereq_chunk_size = "all"
args = ["{basename}",
        "${APPLY_CAL_REDUNDANT_AVERAGE_OPTS:nbl_per_load}"
       ]

# [CLEAN_FILES]
# prereqs = ["DATA_INSPECT_NOTEBOOK_KNOWN_GOOD",
#            "DATA_INSPECT_NOTEBOOK_MAYBE_GOOD",
#            "DATA_INSPECT_NOTEBOOK_ALL_ANTS",
#            "REDCAL_INSPECT_NOTEBOOK_KNOWN_GOOD",
#            "REDCAL_INSPECT_NOTEBOOK_MAYBE_GOOD",
#            "RFI_INSPECT_NOTEBOOK",
#           ]
# prereq_chunk_size = "all"
# args = ["{basename}"]
