[Options]
makeflow_type = "analysis"
source_script = "~/.bashrc"
base_mem = 15500
base_cpu = 1
timeout = "24h"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR2/src/hera_pipelines/pipelines/h6c/idr2/v3/post-lstbin/task_scripts"
conda_env = "h6c_idr2"
batch_system = "slurm"

[WorkFlow]
actions = ["CORNER_TURN",
          ]

[CORNER_TURN]
args = ["{basename}",]
