[Options]
makeflow_type = "analysis"
source_script = "~/.bashrc"
base_mem = 15500
base_cpu = 1
timeout = "24h"
path_to_do_scripts = "/lustre/aoc/projects/hera/h6c-analysis/IDR2/src/hera_pipelines/pipelines/h6c/idr2/v2/post-lstbin/task_scripts"
conda_env = "h6c_idr2"
batch_system = "slurm"

[NOTEBOOK_OPTS]
nb_template_dir = '/lustre/aoc/projects/hera/h6c-analysis/IDR2/src/hera_notebook_templates/notebooks'

[SPECTRAL_POSTPROCESSING_OPTS]
band_str = "50.1~62.2,63.7~73.5,74.6~85.4,108.1~115.8,117.3~124.4,125.5~135.9,138.8~147.1,150.3~161.4,161.5~169.9,171.9~180.8,181.6~196.4,198.6~209.7,212.3~220.5,223.8~231.1"  # MHz
already_inpainted = true
perform_inpaint = false
inpaint_min_dly = 500.0  # ns
inpaint_horizon = 1.0
inpaint_standoff = 0.0
inpaint_eigenval_cutoff = 1e-12
perform_dly_filt = false
dly_filt_min_dly = 150.0  # ns
dly_filt_horizon = 1.0
dly_filt_standoff = 0.0
dly_filt_eigenval_cutoff = 1e-12
use_band_avg_nsamples = true
fm_cut_freq = 100000000.0  # Hz
pixel_flag_cut = 0.0
channel_flag_cut = 0.0

[TEMPORAL_POSTPROCESSING_OPTS]
integration_flag_cut = 0.2
ninterleave = 4
xtalk_fr = 0.01  # mHz
fr_spectra_file = "/lustre/aoc/projects/hera/zmartino/hera_frf/spectra_cache/spectra_cache_hera_core.h5"
fr_quantile_low = 0.05
fr_quantile_high = 0.95
fr_eigenval_cutoff = 1e-12
target_averaging_time = 300  # seconds
use_corr_matrix = true

[PSPEC_OPTS]
efield_healpix_beam_file = "/lustre/aoc/projects/hera/H4C/beams/NF_HERA_Vivaldi_efield_beam_healpix.fits"
taper = "bh"
include_interleave_auto_ps = false
store_window_functions = false

[WorkFlow]
actions = ["SINGLE_BASELINE_POSTPROCESSING_AND_PSPEC",
          ]

[SINGLE_BASELINE_POSTPROCESSING_AND_PSPEC]
args = ["{basename}",
        "${NOTEBOOK_OPTS:nb_template_dir}",
        "${SPECTRAL_POSTPROCESSING_OPTS:band_str}",
        "${SPECTRAL_POSTPROCESSING_OPTS:already_inpainted}",
        "${SPECTRAL_POSTPROCESSING_OPTS:perform_inpaint}",
        "${SPECTRAL_POSTPROCESSING_OPTS:inpaint_min_dly}",
        "${SPECTRAL_POSTPROCESSING_OPTS:inpaint_horizon}",
        "${SPECTRAL_POSTPROCESSING_OPTS:inpaint_standoff}",
        "${SPECTRAL_POSTPROCESSING_OPTS:inpaint_eigenval_cutoff}",
        "${SPECTRAL_POSTPROCESSING_OPTS:perform_dly_filt}",
        "${SPECTRAL_POSTPROCESSING_OPTS:dly_filt_min_dly}",
        "${SPECTRAL_POSTPROCESSING_OPTS:dly_filt_horizon}",
        "${SPECTRAL_POSTPROCESSING_OPTS:dly_filt_standoff}",
        "${SPECTRAL_POSTPROCESSING_OPTS:dly_filt_eigenval_cutoff}",
        "${SPECTRAL_POSTPROCESSING_OPTS:use_band_avg_nsamples}",
        "${SPECTRAL_POSTPROCESSING_OPTS:fm_cut_freq}",
        "${SPECTRAL_POSTPROCESSING_OPTS:pixel_flag_cut}",
        "${SPECTRAL_POSTPROCESSING_OPTS:channel_flag_cut}",
        "${TEMPORAL_POSTPROCESSING_OPTS:integration_flag_cut}",
        "${TEMPORAL_POSTPROCESSING_OPTS:ninterleave}",
        "${TEMPORAL_POSTPROCESSING_OPTS:xtalk_fr}",
        "${TEMPORAL_POSTPROCESSING_OPTS:fr_spectra_file}",
        "${TEMPORAL_POSTPROCESSING_OPTS:fr_quantile_low}",
        "${TEMPORAL_POSTPROCESSING_OPTS:fr_quantile_high}",
        "${TEMPORAL_POSTPROCESSING_OPTS:fr_eigenval_cutoff}",
        "${TEMPORAL_POSTPROCESSING_OPTS:target_averaging_time}",
        "${TEMPORAL_POSTPROCESSING_OPTS:use_corr_matrix}",
        "${PSPEC_OPTS:efield_healpix_beam_file}",
        "${PSPEC_OPTS:taper}",
        "${PSPEC_OPTS:include_interleave_auto_ps}",
        "${PSPEC_OPTS:store_window_functions}",
        ]
