[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/post_processing/v6/pre_lstbin/task_scripts"
conda_env = "hera3dev"
source_script = "~/.bashrc"
base_mem = 8000
base_cpu = 1
timeout = "24h"
mail_user = "aaronew+nrao@berkeley.edu"
chunk_size = 8
#spw_ranges='10~320,515~717,770~1090'
spw_ranges='10~105,150~320,515~615,665~717,770~1090'
label = "all-bands-allbls-long-delay-clean-include-variable-ants-fix-gain-jumps"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/lustre/hera_pipelines/pipelines/h4c/rtp/v1/stage_2_a_priori_flags_include_variable/"
nbl_per_load = 100
t_avg = 300.0
include_diffs = "true"

[CAL_SMOOTH_OPTS]
freq_scale = 10
time_scale = 864000
tol = 1e-6
filter_mode = "rect"
window = "tukey"
maxiter = 100
alpha = 0.3
freq_threshold = 1.0
time_threshold = 1.0
ant_threshold = 0.5
lst_blacklists = "0-1.3 2.5-4.3 10.6-11.5 11.9-14.3 22.3-1.3"

[GAIN_JUMP_INSPECT_OPTS]
nb_template_dir = "/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks/"
nb_output_repo = "/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks/"
git_push = "False"

[DELAY_OPTS]
tol = 1e-9
standoff = 50.0
min_dly = 750.0
calibration = "none"
filter_mode = "DPSS"
#spw_ranges = "0~310,310~832"
spw_ranges = "0~265,265~737"

# we may want to consider another flagging round after delay filtering.

[FR_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.025
tol = 1e-9
# inpaint beyond frate limit by this much.
frate_standoff = 0.0
min_frate = 0.5
yaml_flag_file="/lustre/aoc/projects/hera/H4C/h4c_software/hera_pipelines/pipelines/h4c/post_processing/v6/pre_lstbin/flag_yamls/post_process_flags.yaml"

[PSPEC_OPTS]
pstokes="pI"
beam_file="/lustre/aoc/projects/hera/H4C/beams/NF_HERA_Vivaldi_efield_beam_healpix"
#spw_ranges="0~95,95~180,180~265,265~365,365~430,430~515,515~600,600~685"
spw_ranges="0~95,95~180,180~265,265~365,365~417,417~497,497~577,577~657,657~737"
#spw_ranges="0~102,102~204,204~310,310~410,410~512,512~592,592~672,672~752,752~832"
nsamples=100
seed=10

[FILTER_NOTEBOOK_OPTS]
nb_template_dir = "/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks/"
nb_output_repo = "/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks/"
git_push = "False"
nreds = 6
max_bls_per_redgrp = 4
nskip = 3

[POWER_SPECTRUM_NOTEBOOK_OPTS]
nb_template_dir = "/lustre/aoc/projects/hera/H4C/h4c_software/hera_notebook_templates/notebooks/"
nb_output_repo = "/lustre/aoc/projects/hera/H4C/h4c_software/H4C_Notebooks/"
git_push = "False"
spws = "0,1,2,3,4,5,6,7"
lst_fields="1~3,4.2~6.2"
grp_skip = 10
blp_skip = 2
field_labels = "1,2"
max_plots_per_row = 10

############################################################################################################

[WorkFlow]
actions = ["FIRSTCAL_META_MEDIANS",
           "INSERT_OMNICAL_MEDIANS",
           "GET_RED_DEGEN",
           "CAL_SMOOTH_TIME_DEGEN",
           "MULT_RED_DEGEN",
           "CAL_SMOOTH_FREQ",
           "GAIN_JUMP_INSPECT",
           "PRE_CHUNK",
           "DELAY",
           "XTALK",
           #"TIME_INPAINT",
           "RECONSTITUTE",
           #"TRANSFER_FLAGS",
           "TIME_AVERAGE",
           "RECONSTITUTE_TAVG",
           "PSTOKES",
           "PSPEC",
           "AUTOERRORS",
           #BOOTSTRAPERRORS,
           #"FILTER_NOTEBOOK",
           "POWER_SPECTRUM_NOTEBOOK"]
           #"POWER_SPECTRUM_SUMMARY_NOTEBOOK",
           #"CLEANUP_KEEP_FGFILLED"]

[FIRSTCAL_META_MEDIANS]
mem=16000
chunk_size = 1
stride_length = "all"
time_centered = false
args = ["{basename}", "${Options:label}"]

[INSERT_OMNICAL_MEDIANS]
prereqs = "FIRSTCAL_META_MEDIANS"
chunk_size = 1
prereq_chunk_size = "all"
mem=16000
args=["{basename}", "${Options:label}"]

[GET_RED_DEGEN]
prereqs="INSERT_OMNICAL_MEDIANS"
mem=16000
args=["{basename}", "${Options:label}"]

[CAL_SMOOTH_TIME_DEGEN]
prereqs = "GET_RED_DEGEN"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args = ["{basename}",
        "${Options:label}",
        "${CAL_SMOOTH_OPTS:time_scale}",
        "${CAL_SMOOTH_OPTS:tol}",
        "${CAL_SMOOTH_OPTS:time_threshold}",
        "${CAL_SMOOTH_OPTS:ant_threshold}",
        "${CAL_SMOOTH_OPTS:lst_blacklists}"]

[MULT_RED_DEGEN]
prereqs = "CAL_SMOOTH_TIME_DEGEN"
prereq_chunk_size = "all"
mem=16000
args=["{basename}", "${Options:label}"]

[CAL_SMOOTH_FREQ]
prereqs = "MULT_RED_DEGEN"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args=["{basename}",
      "${Options:label}",
      "${CAL_SMOOTH_OPTS:freq_scale}",
      "${CAL_SMOOTH_OPTS:tol}",
      "${CAL_SMOOTH_OPTS:freq_threshold}",
      "${CAL_SMOOTH_OPTS:ant_threshold}"]

[GAIN_JUMP_INSPECT]
prereqs = "CAL_SMOOTH_FREQ"
prereq_chunk_size = "all"
chunk_size = 1
stride_length = "all"
time_centered = false
mem = 128000
args=["{basename}",
      "${GAIN_JUMP_INSPECT_OPTS:nb_template_dir}",
      "${GAIN_JUMP_INSPECT_OPTS:nb_output_repo}",
      "${GAIN_JUMP_INSPECT_OPTS:git_push}",
      "${Options:label}"]

[PRE_CHUNK]
prereqs = "CAL_SMOOTH_FREQ"
prereq_chunk_size = "all"
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}",
    "${Options:chunk_size}",
    "${Options:spw_ranges}", "${Options:yaml_dir}"]

[DELAY]
prereqs = "PRE_CHUNK"
prereq_chunk_size = 1
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}",
       "${Options:include_diffs}", "${Options:label}", "${DELAY_OPTS:tol}",
       "${DELAY_OPTS:standoff}",   "${DELAY_OPTS:min_dly}", , "${Options:cache_dir}",
       "${DELAY_OPTS:filter_mode}",
       "${Options:nbl_per_load}", "${DELAY_OPTS:spw_ranges}", "${FR_OPTS:yaml_flag_file}"]

[XTALK]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:include_diffs}",
       "${Options:label}", "${FR_OPTS:tol}",
       "${FR_OPTS:frmax0}", "${FR_OPTS:frmax1}",
       "${Options:cache_dir}", "${DELAY_OPTS:spw_ranges}", "${FR_OPTS:yaml_flag_file}"]


#[TIME_INPAINT]
#prereqs = "XTALK"
#prereq_chunk_size=1
#chunk_size=1
#stride_length="${Options:chunk_size}"
#mem = 16000
#args = ["{basename}", "${Options:include_diffs}",
       #"${Options:label}", "${FR_OPTS:tol}",
       #"${FR_OPTS:frate_standoff}", "${FR_OPTS:min_frate}",
       #"${Options:cache_dir}", "${DELAY_OPTS:spw_ranges}", "${FR_OPTS:yaml_flag_file}"]



[RECONSTITUTE]
prereqs = "XTALK"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:include_diffs}",
       "${Options:label}"]


#[TRANSFER_FLAGS]
#prereqs = "RECONSTITUTE"
#prereq_chunk_size=1
#chunk_size=1
#stride_length="${Options:chunk_size}"
#mem = 16000
#args = ["{basename}", "${Options:include_diffs}",
      #"${Options:label}"]


[TIME_AVERAGE]
prereqs = "RECONSTITUTE"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:include_diffs}",
       "${Options:label}", "${Options:t_avg}"]

[RECONSTITUTE_TAVG]
prereqs = "TIME_AVERAGE"
prereq_chunk_size="all"
chunk_size=1
stride_length="${Options:chunk_size}"
mem = 16000
args = ["{basename}", "${Options:include_diffs}",
      "${Options:label}"]

[PSTOKES]
prereqs="RECONSTITUTE_TAVG"
prereq_chunk_size=1
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}",
     "${Options:label}", "${PSPEC_OPTS:pstokes}"]

[PSPEC]
prereqs = "PSTOKES"
prereq_chunk_size = 1
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}",
     "${PSPEC_OPTS:beam_file}", "${PSPEC_OPTS:spw_ranges}"]

[AUTOERRORS]
prereqs = "PSPEC"
prereq_chunk_size = 1
mem=16000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}", "${PSPEC_OPTS:beam_file}"]

[BOOTSTRAPERRORS]
prereqs = "AUTOERRORS"
prereq_chunk_size = 1
mem=32000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:include_diffs}", "${Options:label}", "${PSPEC_OPTS:nsamples}", "${PSPEC_OPTS:seed}"]

#[FILTER_NOTEBOOK]
#prereqs="AUTOERRORS"
#prereq_chunk_size="all"
#mem=128000
#chunk_size=1
#stride_length="all"
#time_centered = false
#args=["{basename}", "${FILTER_NOTEBOOK_OPTS:nb_template_dir}", "${FILTER_NOTEBOOK_OPTS:nb_output_repo}",
#      "${FILTER_NOTEBOOK_OPTS:git_push}", "${Options:label}", "${FILTER_NOTEBOOK_OPTS:nreds}",
#      "${FILTER_NOTEBOOK_OPTS:max_bls_per_redgrp}", "${FILTER_NOTEBOOK_OPTS:nskip}", "${PSPEC_OaPTS:spw_ranges}"]

[POWER_SPECTRUM_NOTEBOOK]
prereqs="AUTOERRORS"
prereq_chunk_size="all"
mem=128000
chunk_size=1
stride_length="all"
time_centered=false
args=["{basename}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:nb_template_dir}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:nb_output_repo}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:git_push}", "${Options:label}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:spws}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:lst_fields}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:grp_skip}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:blp_skip}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:field_labels}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:max_plots_per_row}"]

[POWER_SPECTRUM_SUMMARY_NOTEBOOK]
prereqs="POWER_SPECTRUM_NOTEBOOK"
prereq_chunk_size="all"
mem=128000
chunk_size=1
stride_length="all"
time_centered=false
args=["{basename}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:nb_template_dir}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:nb_output_repo}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:git_push}", "${Options:label}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:spws}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:lst_fields}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:grp_skip}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:blp_skip}", "${POWER_SPECTRUM_NOTEBOOK_OPTS:field_labels}",
      "${POWER_SPECTRUM_NOTEBOOK_OPTS:max_plots_per_row}"]

[CLEANUP_KEEP_FGFILLED]
prereqs= "POWER_SPECTRUM_NOTEBOOK"
prereq_chunk_size = "all"
mem=8000
chunk_size=1
stride_length="${Options:chunk_size}"
args=["{basename}", "${Options:label}"]
