[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/filtering_task_scripts/"
path_to_observer_bad_ants = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/observer_bad_ants"
path_to_analysis_bad_ants = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/analysis_bad_ants"
conda_env = "hera3"
source_script = "~/.bashrc"
base_mem = 16000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"

[GLOBAL_OPTS]
data_ext = 'smooth_abs_vis.uvh5'

[DELAY_OPTS]
label = "sum"
spw0 = 0
spw1 = 256
tol = 1e-9
standoff = 200
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
#calibration = "smooth_abs.calfits"
calibration = "none"

# we may want to consider another flagging round after delay filtering.

[XTALK_BASELINE_PARALLELIZED_OPTS]
label = "sum"
# frmax0 = 0.024 # max_frate = frmax0 * bl_len + frmax1
# frmax1 = -0.229
# dividing this by two for low band.
frmax0 = 0.012
frmax1 = -0.115
tol = 1e-9
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"

# Reconstitute the xtalk waterfalls.

[RECONSTITUTE_OPTS]
label = "sum"

[FILTER_CLEANUP_OPTS]
clear_xtalk_cache = false
clear_delay_cache = false
clear_delay = false



############################################################################################################

[WorkFlow]
actions = ["DELAY",
           "XTALK_BASELINE_PARALLELIZED",
           "RECONSTITUTE",
	         "FILTER_CLEANUP"]

[DELAY]
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${DELAY_OPTS:calibration}", "${DELAY_OPTS:label}",
        "${DELAY_OPTS:spw0}", "${DELAY_OPTS:spw1}", "${DELAY_OPTS:tol}",
        "${DELAY_OPTS:standoff}", "${DELAY_OPTS:cache_dir}"]
chunk_size = 1
stride_length = 1
time_centered = false

[XTALK_BASELINE_PARALLELIZED]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size = 1
stride_length = 1
mem = 128000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${XTALK_BASELINE_PARALLELIZED_OPTS:label}", "${XTALK_BASELINE_PARALLELIZED_OPTS:tol}",
        "${XTALK_BASELINE_PARALLELIZED_OPTS:frmax0}", "${XTALK_BASELINE_PARALLELIZED_OPTS:frmax1}", "${XTALK_BASELINE_PARALLELIZED_OPTS:cache_dir}"]

[RECONSTITUTE]
prereqs = "XTALK_BASELINE_PARALLELIZED"
prereq_chunk_size="all"
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${RECONSTITUTE_OPTS:label}"]

[FILTER_CLEANUP]
prereqs = "RECONSTITUTE"
prereq_chunk_size="all"
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${FILTER_CLEANUP_OPTS:clear_xtalk_cache}", "${FILTER_CLEANUP_OPTS:clear_delay_cache}", "${XTALK_BASELINE_PARALLELIZED_OPTS:cache_dir}", "${DELAY_OPTS:cache_dir}",
       		      "${FILTER_CLEANUP_OPTS:clear_delay}", "${XTALK_BASELINE_PARALLELIZED_OPTS:label}", "${DELAY_OPTS:label}"]
