[Options]
makeflow_type = "analysis"
path_to_do_scripts = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/filtering_task_scripts/"
path_to_observer_bad_ants = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/observer_bad_ants"
path_to_analysis_bad_ants = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/analysis_bad_ants"
conda_env = "hera3"
source_script = "~/.bashrc"
base_mem = 16000
base_cpu = 1
timeout = "24h"
pbs_mail_user = "aaronew+nrao@berkeley.edu"

[GLOBAL_OPTS]
data_ext = 'smooth_abs_vis.uvh5'
spw0 = 0
spw1 = 320
label = "low-band"
cache_dir = "/lustre/aoc/projects/hera/aewallwi/filter_cache/"
pols = "ee nn"
yaml_dir = "/users/aewallwi/hera_pipelines/pipelines/h3c/idr3/v1/flagging_yamls"

[CAL_SMOOTH_SIMPLE_OPTS]
freq_scale = 10.0
time_threshold = 0.05
freq_threshold = 1.0
ant_threshold = 0.5
lst_blacklists = "0-1.3 2.5-4.3 5.0-5.7 6.5-9.1 10.6-11.5 11.9-14.3 16.3-1.3"
flag_ext="og_flags1"

[APPLY_CAL_REDUNDANT_AVERAGE_OPTS]
nbl_per_load = 0

[DELAY_OPTS]
tol = 1e-9
standoff = 300
calibration = "none"

# we may want to consider another flagging round after delay filtering.

[XTALK_BASELINE_PARALLELIZED_OPTS]
# dividing this by two for low band.
frmax0 = 0.0
frmax1 = 0.1
tol = 1e-9

[FILTER_CLEANUP_OPTS]
clear_xtalk_cache = false
clear_delay_cache = false
clear_delay = false



############################################################################################################

[WorkFlow]
actions = ["CAL_SMOOTH_SIMPLE",
           "APPLY_CAL_REDUNDANT_AVERAGE",
           "DELAY",
           "XTALK_BASELINE_PARALLELIZED",
           "RECONSTITUTE",
	         "FILTER_CLEANUP"]

[CAL_SMOOTH_SIMPLE]
mem = 64000
args = ["{basename}", "${CAL_SMOOTH_SIMPLE_OPTS:freq_scale}", "${CAL_SMOOTH_SIMPLE_OPTS:time_threshold}",
        "${CAL_SMOOTH_SIMPLE_OPTS:freq_threshold}", "${CAL_SMOOTH_SIMPLE_OPTS:ant_threshold}",
        "${CAL_SMOOTH_SIMPLE_OPTS:flag_ext}",
        "${GLOBAL_OPTS:spw0}", "${GLOBAL_OPTS:spw1}",
	"${GLOBAL_OPTS:label}", "${GLOBAL_OPTS:yaml_dir}",
	"${CAL_SMOOTH_SIMPLE_OPTS:lst_blacklists}"]
chunk_size=1
stride_length=1

[APPLY_CAL_REDUNDANT_AVERAGE]
prereqs = "CAL_SMOOTH_SIMPLE"
prereq_chunk_size = "all"
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:label}", "${GLOBAL_OPTS:data_ext}",
        "${APPLY_CAL_REDUNDANT_AVERAGE_OPTS:nbl_per_load}", "${GLOBAL_OPTS:pols}"]
chunk_size = 1
stride_length = 1

[DELAY]
prereqs="APPLY_CAL_REDUNDANT_AVERAGE"
prereq_chunk_size = 1
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${DELAY_OPTS:calibration}", "${GLOBAL_OPTS:label}",
        "${GLOBAL_OPTS:spw0}", "${GLOBAL_OPTS:spw1}", "${DELAY_OPTS:tol}",
        "${DELAY_OPTS:standoff}", "${GLOBAL_OPTS:cache_dir}"]
chunk_size = 1
stride_length = 1
time_centered = false

[XTALK_BASELINE_PARALLELIZED]
prereqs = "DELAY"
prereq_chunk_size="all"
chunk_size = 1
stride_length = 1
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:label}", "${XTALK_BASELINE_PARALLELIZED_OPTS:tol}",
        "${XTALK_BASELINE_PARALLELIZED_OPTS:frmax0}", "${XTALK_BASELINE_PARALLELIZED_OPTS:frmax1}", "${GLOBAL_OPTS:cache_dir}"]

[RECONSTITUTE]
prereqs = "XTALK_BASELINE_PARALLELIZED"
prereq_chunk_size="all"
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${GLOBAL_OPTS:label}"]

[FILTER_CLEANUP]
prereqs = "RECONSTITUTE"
prereq_chunk_size="all"
mem = 64000
args = ["{basename}", "${GLOBAL_OPTS:data_ext}", "${FILTER_CLEANUP_OPTS:clear_xtalk_cache}", "${FILTER_CLEANUP_OPTS:clear_delay_cache}", "${GLOBAL_OPTS:cache_dir}", "${GLOBAL_OPTS:cache_dir}",
       		      "${FILTER_CLEANUP_OPTS:clear_delay}", "${GLOBAL_OPTS:label}", "${GLOBAL_OPTS:label}"]
